// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/fdaPDE2.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_FPCA_CS_Laplacian_2D_GeoStatNodes();
RcppExport SEXP _rcpp_module_boot_FPCA_CS_Laplacian_2D_GeoStatLocations();
RcppExport SEXP _rcpp_module_boot_FPCA_CS_Laplacian_3D_GeoStatNodes();
RcppExport SEXP _rcpp_module_boot_FPCA_Laplacian_2D_GeoStatNodes_GCV();
RcppExport SEXP _rcpp_module_boot_FPCA_Laplacian_2D_GeoStatLocations_GCV();
RcppExport SEXP _rcpp_module_boot_FPCA_Laplacian_3D_GeoStatNodes_GCV();
RcppExport SEXP _rcpp_module_boot_FPCA_Laplacian_2D_GeoStatNodes_fixed();
RcppExport SEXP _rcpp_module_boot_FPCA_Laplacian_2D_GeoStatLocations_fixed();
RcppExport SEXP _rcpp_module_boot_FPCA_Laplacian_3D_GeoStatNodes_fixed();
RcppExport SEXP _rcpp_module_boot_FPLSR_Laplacian_2D_GeoStatNodes();
RcppExport SEXP _rcpp_module_boot_FPLSR_Laplacian_2D_GeoStatLocations();
RcppExport SEXP _rcpp_module_boot_FRPDE_Laplacian_2D_GeoStatNodes();
RcppExport SEXP _rcpp_module_boot_FRPDE_Laplacian_2D_GeoStatLocations();
RcppExport SEXP _rcpp_module_boot_FRPDE_Laplacian_Surface_GeoStatNodes();
RcppExport SEXP _rcpp_module_boot_FRPDE_Laplacian_Surface_GeoStatLocations();
RcppExport SEXP _rcpp_module_boot_Laplacian_2D_Order1();
RcppExport SEXP _rcpp_module_boot_ConstantCoefficients_2D_Order1();
RcppExport SEXP _rcpp_module_boot_SpaceVarying_2D_Order1();
RcppExport SEXP _rcpp_module_boot_Laplacian_Surface_Order1();
RcppExport SEXP _rcpp_module_boot_Laplacian_3D_Order1();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_FPCA_CS_Laplacian_2D_GeoStatNodes", (DL_FUNC) &_rcpp_module_boot_FPCA_CS_Laplacian_2D_GeoStatNodes, 0},
    {"_rcpp_module_boot_FPCA_CS_Laplacian_2D_GeoStatLocations", (DL_FUNC) &_rcpp_module_boot_FPCA_CS_Laplacian_2D_GeoStatLocations, 0},
    {"_rcpp_module_boot_FPCA_CS_Laplacian_3D_GeoStatNodes", (DL_FUNC) &_rcpp_module_boot_FPCA_CS_Laplacian_3D_GeoStatNodes, 0},
    {"_rcpp_module_boot_FPCA_Laplacian_2D_GeoStatNodes_GCV", (DL_FUNC) &_rcpp_module_boot_FPCA_Laplacian_2D_GeoStatNodes_GCV, 0},
    {"_rcpp_module_boot_FPCA_Laplacian_2D_GeoStatLocations_GCV", (DL_FUNC) &_rcpp_module_boot_FPCA_Laplacian_2D_GeoStatLocations_GCV, 0},
    {"_rcpp_module_boot_FPCA_Laplacian_3D_GeoStatNodes_GCV", (DL_FUNC) &_rcpp_module_boot_FPCA_Laplacian_3D_GeoStatNodes_GCV, 0},
    {"_rcpp_module_boot_FPCA_Laplacian_2D_GeoStatNodes_fixed", (DL_FUNC) &_rcpp_module_boot_FPCA_Laplacian_2D_GeoStatNodes_fixed, 0},
    {"_rcpp_module_boot_FPCA_Laplacian_2D_GeoStatLocations_fixed", (DL_FUNC) &_rcpp_module_boot_FPCA_Laplacian_2D_GeoStatLocations_fixed, 0},
    {"_rcpp_module_boot_FPCA_Laplacian_3D_GeoStatNodes_fixed", (DL_FUNC) &_rcpp_module_boot_FPCA_Laplacian_3D_GeoStatNodes_fixed, 0},
    {"_rcpp_module_boot_FPLSR_Laplacian_2D_GeoStatNodes", (DL_FUNC) &_rcpp_module_boot_FPLSR_Laplacian_2D_GeoStatNodes, 0},
    {"_rcpp_module_boot_FPLSR_Laplacian_2D_GeoStatLocations", (DL_FUNC) &_rcpp_module_boot_FPLSR_Laplacian_2D_GeoStatLocations, 0},
    {"_rcpp_module_boot_FRPDE_Laplacian_2D_GeoStatNodes", (DL_FUNC) &_rcpp_module_boot_FRPDE_Laplacian_2D_GeoStatNodes, 0},
    {"_rcpp_module_boot_FRPDE_Laplacian_2D_GeoStatLocations", (DL_FUNC) &_rcpp_module_boot_FRPDE_Laplacian_2D_GeoStatLocations, 0},
    {"_rcpp_module_boot_FRPDE_Laplacian_Surface_GeoStatNodes", (DL_FUNC) &_rcpp_module_boot_FRPDE_Laplacian_Surface_GeoStatNodes, 0},
    {"_rcpp_module_boot_FRPDE_Laplacian_Surface_GeoStatLocations", (DL_FUNC) &_rcpp_module_boot_FRPDE_Laplacian_Surface_GeoStatLocations, 0},
    {"_rcpp_module_boot_Laplacian_2D_Order1", (DL_FUNC) &_rcpp_module_boot_Laplacian_2D_Order1, 0},
    {"_rcpp_module_boot_ConstantCoefficients_2D_Order1", (DL_FUNC) &_rcpp_module_boot_ConstantCoefficients_2D_Order1, 0},
    {"_rcpp_module_boot_SpaceVarying_2D_Order1", (DL_FUNC) &_rcpp_module_boot_SpaceVarying_2D_Order1, 0},
    {"_rcpp_module_boot_Laplacian_Surface_Order1", (DL_FUNC) &_rcpp_module_boot_Laplacian_Surface_Order1, 0},
    {"_rcpp_module_boot_Laplacian_3D_Order1", (DL_FUNC) &_rcpp_module_boot_Laplacian_3D_Order1, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_fdaPDE2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
